### login sucess
POST http://localhost:3455/login
Content-Type: application/json

{"username":"administrator","password":"admin"}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  var jwt=response.body
  client.global.set("jwt", response.body)
});
%}

###

GET http://localhost:3045/api/manufacturers
Authorization: Bearer {{jwt}}

###

